[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "email-validator>=2.2.0",
    "pandas>=2.3.1",
    "plotly>=6.2.0",
    "streamlit>=1.46.1",
]
